"""Nginx configuration generator for tollbot."""
import os


class NginxConfigurator:
    """Generate nginx configuration for tollbot."""

    def __init__(self, domain: str, config_dir: str = "/etc/tollbot"):
        """Initialize configurator.

        Args:
            domain: Domain name
            config_dir: Tollbot configuration directory
        """
        self.domain = domain
        self.config_dir = config_dir

    def generate(self):
        """Generate nginx configuration files."""
        nginx_dir = os.path.join(self.config_dir, "nginx")
        os.makedirs(nginx_dir, exist_ok=True)

        # Generate include file
        include_path = os.path.join(nginx_dir, "tollbot-include.conf")
        with open(include_path, "w") as f:
            f.write(self._get_include_config())

        # Generate domain-specific config
        domain_path = os.path.join(nginx_dir, f"{self.domain}.conf")
        with open(domain_path, "w") as f:
            f.write(self._get_domain_config())

    def _get_include_config(self) -> str:
        """Get nginx include configuration."""
        return """# Tollbot payment validation configuration
# Generated by tollbot - do not edit manually

# Payment validation location
location /__tollbot__/validate {
    default_type application/json;
    content_by_lua_file /etc/tollbot/lua/payment_filter.lua;
}

# Payment request endpoint
location /__tollbot__/request-payment {
    default_type application/json;
    content_by_lua_file /etc/tollbot/lua/request_payment.lua;
}

# Payment status endpoint
location /__tollbot__/status {
    default_type application/json;
    return 200 '{"status": "ok"}';
}
"""

    def _get_domain_config(self) -> str:
        """Get domain-specific nginx configuration."""
        return f"""# Tollbot configuration for {self.domain}
# Include tollbot payment validation

http {{
    # Include tollbot payment validation
    include {os.path.join(self.config_dir, "nginx", "tollbot-include.conf")};
}}

server {{
    listen 80;
    listen 443 ssl;
    server_name {self.domain};

    # SSL configuration (adjust as needed)
    ssl_certificate /etc/ssl/certs/{self.domain}.crt;
    ssl_certificate_key /etc/ssl/private/{self.domain}.key;

    # Protect API endpoints
    location /api/ {{
        # Check payment token
        access_by_lua_block {{
            tollbot.payment_filter.validate()
        }}

        proxy_pass http://localhost:8080;
    }}

    # Serve static content
    location / {{
        root /var/www/{self.domain}/html;
        index index.html;
    }}
}}
"""

    def reload(self):
        """Reload nginx configuration."""
        # Check if nginx is running
        if os.path.exists("/var/run/nginx.pid"):
            os.system("nginx -s reload")
            print("Nginx reloaded successfully")
        else:
            print("Nginx is not running")

    def test_config(self) -> bool:
        """Test nginx configuration syntax.

        Returns:
            bool: True if configuration is valid
        """
        result = os.system("nginx -t 2>/dev/null")
        return result == 0
